version: '3.5'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      PG_HOST: pg
    volumes:
      - /alpaca_web:/app
    ports:
      - 5000:5000
    depends_on:
      - pg
      - redis
  pg:
    image: postgres:13.3
    environment:
      POSTGRES_DB: alpaca
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
    - 5432:5432
  redis:
    image: redis:6.2
    ports:
      - 6379:6379
    volumes:
      - ./config/redis-docker/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
