version: '3.5'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ""
    image: alpaca00/opponent
    env_file: .env
    environment:
      PG_HOST: pg
      R_HOST: redis
    volumes:
      - /squash-opponent:/app
    expose:
      - 8000
      - 443
    ports:
      - "8000:8000"
      - "443:443"
    depends_on:
      - pg
      - redis
    command: gunicorn -w 1 -b 0.0.0.0:443 wsgi:app
  pg:
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - ./data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
  redis:
    image: redis:6.2
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis-docker/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  nginx-ssl-proxy:
    image: danieldent/nginx-ssl-proxy
    container_name: nginx
    restart: always
    environment:
      UPSTREAM: 0.0.0.0:80
      SERVERNAME: lviv-squash-team.com.ua
      EXTRANAMES: www.lviv-squash-team.com.ua
    ports:
      "8449:443"
      "8080:80"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
