name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@main
      - name: Test
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run coverage run -m pytest -s -H -sv --cov-config .coveragerc --tb=short tests/tests_ui/test_smoke/test_regression/
          pipenv run coverage xml -o coverage.xml
      - name: Upload pytest test results
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          path: coverage.xml

