name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      SPS: ${{ secrets.SPS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      HOST: ${{ secrets.HOST }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USERNAME_ADMIN: ${{ secrets.USERNAME_ADMIN }}
      PASSWORD_ADMIN: ${{ secrets.PASSWORD_ADMIN }}
    steps:
      - name: Fetch
        uses: actions/checkout@main
      - name: Export env
        run: env
      - name: Test runner pytest
#        if: "contains(github.event.head_commit.message, 'CONDITION PYTEST')"
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv install psycopg2-binary
          pipenv run coverage run -m pytest -sv --cov-config .coveragerc tests/tests_ui/tests_regression/
          pipenv run coverage run -m pytest -sv -H --cov-config .coveragerc tests/tests_ui/test_smoke/test_regression/
          pipenv run coverage xml -o coverage.xml
#          sudo ln -s /var/run/postgresql/.s.PGSQL.5432 /tmp/.s.PGSQL.5432          
      - name: Upload pytest test results
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          path: coverage.xml
