name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      SPS: ${{ secrets.SPS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      HOST: ${{ secrets.HOST }}
      USER_EMAIL: ${{ secrets.USER_EMAIL }}
      USERNAME_ADMIN: ${{ secrets.USERNAME_ADMIN }}
    steps:
      - name: Fetch
        uses: actions/checkout@main
      - name: Test runner pytest
#        if: "contains(github.event.head_commit.message, 'CONDITION PYTEST')"
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run coverage run -m pytest -sv --cov-config .coveragerc -v -m "regression"
          pipenv run coverage run -m pytest -sv -H --cov-config .coveragerc -v -m "smoke"
          pipenv run coverage xml -o coverage.xml
      - name: Upload pytest test results
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          path: coverage.xml
