name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      SPS: ${{ secrets.SPS }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      USER_PASSWORD:  ${{ secrets.USER_PASSWORD }}
    steps:
      - name: Fetch
        uses: actions/checkout@main
      - name: Test
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run pytest -s -H tests/tests_ui/test_smoke/test_regression/
#          pipenv run coverage run -m pytest -sv -H --cov-config .coveragerc --tb=short tests/tests_ui/test_smoke/test_regression/
#          pipenv run coverage xml -o coverage.xml
      - name: Upload pytest test results
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          path: coverage.xml

