name: Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        uses: actions/checkout@main
      - name: Test
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run coverage run -m pytest -s -H -sv --cov-config .coveragerc --cov-report xml:coverage.xml --tb=short tests/tests_ui/test_smoke/test_app_photo_gallery.py
          pipenv run coverage report -m
      - name: Upload
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

